// <auto-generated />
using System;
using KalyanamMatrimony.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KalyanamMatrimony.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200801094607_First Step")]
    partial class FirstStep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KalyanamMatrimony.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<int>("OrgId");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "f928927f-32a8-4c4f-bbca-dc2a2605c900", AccessFailedCount = 0, ConcurrencyStamp = "e7777f79-47db-4972-9075-e7631052ce98", Email = "sunil.pashikanti@gmail.com", EmailConfirmed = true, LockoutEnabled = false, NormalizedEmail = "SUNIL.PASHIKANTI@GMAIL.COM", NormalizedUserName = "SUNIL.PASHIKANTI@GMAIL.COM", OrgId = 0, PasswordHash = "AQAAAAEAACcQAAAAEKOxDKoa+XqIA/lRQDkZD1MyGLLEaC1lD0B1VaGEU68HwmV7aEbveLexXGT6qfChQQ==", PhoneNumberConfirmed = false, SecurityStamp = "TXEFASMBK2TBWRP42UFH6KKKHHLFKAXD", TwoFactorEnabled = false, UserName = "sunil.pashikanti@gmail.com" }
                    );
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssistantCount");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LicenseName");

                    b.Property<int>("LicenseType");

                    b.Property<float>("MonthsCount");

                    b.Property<string>("PayLink");

                    b.Property<float>("Price");

                    b.Property<int>("UsersCount");

                    b.HasKey("LicenseId");

                    b.ToTable("Licenses");

                    b.HasData(
                        new { LicenseId = 1, AssistantCount = 2, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 350, DateTimeKind.Local), Description = "Free Trial", IsActive = true, LicenseName = "Free Trial", LicenseType = 0, MonthsCount = 0.16f, Price = 0f, UsersCount = 6 },
                        new { LicenseId = 2, AssistantCount = 0, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Starter - 10 Users Per Month", IsActive = true, LicenseName = "10 Users Per Month", LicenseType = 1, MonthsCount = 1f, Price = 200f, UsersCount = 10 },
                        new { LicenseId = 3, AssistantCount = 0, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Starter - 10 Users Per Year", IsActive = true, LicenseName = "10 Users Per Year", LicenseType = 1, MonthsCount = 12f, Price = 2000f, UsersCount = 10 },
                        new { LicenseId = 4, AssistantCount = 1, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Silver - 25 Users Per Month", IsActive = true, LicenseName = "25 Users Per Month", LicenseType = 1, MonthsCount = 1f, Price = 400f, UsersCount = 25 },
                        new { LicenseId = 5, AssistantCount = 1, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Silver - 25 Users Per Year", IsActive = true, LicenseName = "25 Users Per Year", LicenseType = 1, MonthsCount = 12f, Price = 4000f, UsersCount = 25 },
                        new { LicenseId = 6, AssistantCount = 2, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Golden - 50 Users Per Month", IsActive = true, LicenseName = "50 Users Per Month", LicenseType = 1, MonthsCount = 1f, Price = 600f, UsersCount = 50 },
                        new { LicenseId = 7, AssistantCount = 2, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Golden - 50 Users Per Year", IsActive = true, LicenseName = "50 Users Per Year", LicenseType = 1, MonthsCount = 12f, Price = 6000f, UsersCount = 50 },
                        new { LicenseId = 8, AssistantCount = 3, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Diamond - 75 Users Per Month", IsActive = true, LicenseName = "75 Users Per Month", LicenseType = 1, MonthsCount = 1f, Price = 800f, UsersCount = 75 },
                        new { LicenseId = 9, AssistantCount = 3, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Diamond - 75 Users Per Year", IsActive = true, LicenseName = "75 Users Per Year", LicenseType = 1, MonthsCount = 12f, Price = 8000f, UsersCount = 75 },
                        new { LicenseId = 10, AssistantCount = 4, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Platinum - 100 Users Per Month", IsActive = true, LicenseName = "100 Users Per Month", LicenseType = 1, MonthsCount = 1f, Price = 1000f, UsersCount = 100 },
                        new { LicenseId = 11, AssistantCount = 4, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Platinum - 100 Users Per Year", IsActive = true, LicenseName = "100 Users Per Year", LicenseType = 1, MonthsCount = 12f, Price = 10000f, UsersCount = 100 },
                        new { LicenseId = 12, AssistantCount = 5, CreatedDate = new DateTime(2020, 8, 1, 9, 46, 7, 351, DateTimeKind.Local), Description = "Life Time 1 - Buy the product and host it in your own servers for life time. Pay only for new features or supporting services.", IsActive = true, LicenseName = "Life Time 1", LicenseType = 1, MonthsCount = -1f, Price = 15000f, UsersCount = 100 }
                    );
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.Organisation", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("FullName");

                    b.Property<int>("LicenseId");

                    b.Property<string>("OrgDesc");

                    b.Property<string>("OrgName");

                    b.Property<string>("Phone");

                    b.HasKey("OrgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.PartnerPreference", b =>
                {
                    b.Property<int>("PartnerPreferenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgeFrom");

                    b.Property<int?>("AgeTo");

                    b.Property<string>("BodyType");

                    b.Property<string>("Caste");

                    b.Property<string>("Complexion");

                    b.Property<string>("Description");

                    b.Property<string>("Diet");

                    b.Property<string>("Drink");

                    b.Property<string>("Education");

                    b.Property<int?>("Gender");

                    b.Property<float?>("HeightFrom");

                    b.Property<float?>("HeightTo");

                    b.Property<string>("Location");

                    b.Property<string>("Manglik");

                    b.Property<string>("MaritalStatus");

                    b.Property<string>("MotherTongue");

                    b.Property<string>("Profession");

                    b.Property<string>("ProfileId");

                    b.Property<string>("Religion");

                    b.Property<string>("Smoke");

                    b.Property<string>("SubCaste");

                    b.Property<string>("UserId");

                    b.HasKey("PartnerPreferenceId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("PartnerPreferences");
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.PaymentHistory", b =>
                {
                    b.Property<int>("PaymentHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<int>("LicenseId");

                    b.Property<string>("Name");

                    b.Property<string>("OrderId");

                    b.Property<int>("OrgId");

                    b.Property<string>("PaymentURL");

                    b.Property<string>("Phone");

                    b.Property<string>("RedirectURL");

                    b.Property<string>("Status");

                    b.Property<string>("TransactionId");

                    b.Property<string>("UserId");

                    b.HasKey("PaymentHistoryId");

                    b.ToTable("PaymentHistory");
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.Profile", b =>
                {
                    b.Property<string>("ProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutFamily")
                        .HasMaxLength(200);

                    b.Property<string>("AboutYourself")
                        .HasMaxLength(200);

                    b.Property<int?>("Age");

                    b.Property<string>("AnnualIncome");

                    b.Property<string>("AstroProfile")
                        .HasMaxLength(200);

                    b.Property<string>("BloodGroup");

                    b.Property<string>("BodyType");

                    b.Property<int?>("Brothers");

                    b.Property<string>("Caste");

                    b.Property<string>("Complexion");

                    b.Property<string>("ContactPersonName");

                    b.Property<string>("ContactPersonRelationShip");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CurrentLocation");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Diet");

                    b.Property<string>("Drink");

                    b.Property<string>("Education");

                    b.Property<string>("FamilyValues");

                    b.Property<string>("FatherName");

                    b.Property<string>("FatherOccupation");

                    b.Property<string>("FavoriteCuisine");

                    b.Property<string>("FavoriteMovies");

                    b.Property<string>("FavoriteMusic");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int?>("Gender");

                    b.Property<string>("Gothram");

                    b.Property<bool>("HaveChildren");

                    b.Property<float?>("Height");

                    b.Property<string>("Hobbies");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Manglik");

                    b.Property<string>("MaritalStatus");

                    b.Property<int?>("MarriedBrothers");

                    b.Property<int?>("MarriedSisters");

                    b.Property<string>("MotherName");

                    b.Property<string>("MotherOccupation");

                    b.Property<string>("MotherTongue");

                    b.Property<string>("Nakshatram");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Photo1");

                    b.Property<string>("Photo2");

                    b.Property<string>("Photo3");

                    b.Property<string>("PreferredDress");

                    b.Property<string>("Profession");

                    b.Property<string>("Rasi");

                    b.Property<string>("Religion");

                    b.Property<int?>("Sisters");

                    b.Property<string>("Smoke");

                    b.Property<string>("SpokenLanguages");

                    b.Property<string>("Sports");

                    b.Property<string>("SubCaste");

                    b.Property<string>("University");

                    b.Property<string>("UserId");

                    b.Property<string>("WorkingAt");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "1", ConcurrencyStamp = "80dd6a7f-bcc1-405e-bd38-47691e9da570", Name = "SuperAdmin", NormalizedName = "SUPERADMIN" },
                        new { Id = "2", ConcurrencyStamp = "255b6a9b-049e-4850-8942-54c2bcadc044", Name = "Admin", NormalizedName = "ADMIN" },
                        new { Id = "3", ConcurrencyStamp = "77d0bae2-9220-45f5-a0f0-4f9d1e2723c6", Name = "AdminAssistant", NormalizedName = "ADMINASSISTANT" },
                        new { Id = "4", ConcurrencyStamp = "96ccf17e-54e6-4493-aea4-fcbcc63d0322", Name = "Profile", NormalizedName = "PROFILE" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new { UserId = "f928927f-32a8-4c4f-bbca-dc2a2605c900", RoleId = "1" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KalyanamMatrimony.Models.PartnerPreference", b =>
                {
                    b.HasOne("KalyanamMatrimony.Models.Profile")
                        .WithOne("PartnerPreference")
                        .HasForeignKey("KalyanamMatrimony.Models.PartnerPreference", "ProfileId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KalyanamMatrimony.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KalyanamMatrimony.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalyanamMatrimony.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KalyanamMatrimony.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
